# Generated by Django 4.0.5 on 2022-06-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
