# Generated by Django 4.0.5 on 2022-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_category_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='hello'),
        ),
    ]
