# Generated by Django 4.0.5 on 2022-06-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
